import { useState, type ChangeEvent, type FormEvent } from 'react';
import { ArrowUpRight, Github, Linkedin, Mail, MapPin, Phone } from 'lucide-react';
import SectionWrapper from './SectionWrapper';

interface ContactFormState { name: string; email: string; subject: string; message: string; }
type ContactField = keyof ContactFormState;
const initialForm: ContactFormState = { name: '', email: '', subject: '', message: '' };
const details = [{ icon: Mail, label: 'Email', value: 'abdallamsema69@gmail.com', href: 'mailto:abdallamsema69@gmail.com' }, { icon: Phone, label: 'Phone', value: '+254 112 898 506', href: 'tel:+254112898506' }, { icon: Linkedin, label: 'LinkedIn', value: 'msema-abdalla', href: 'https://www.linkedin.com/in/msema-abdalla' }, { icon: Github, label: 'GitHub', value: 'abdalla-dev453', href: 'https://github.com/abdalla-dev453' }] as const;

export default function Contact() {
  const [form, setForm] = useState<ContactFormState>(initialForm);
  const [submitted, setSubmitted] = useState(false);
  const updateField = (field: ContactField) => (event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setForm((current) => ({ ...current, [field]: event.target.value }));
  const handleSubmit = (event: FormEvent<HTMLFormElement>): void => { event.preventDefault(); setSubmitted(true); setForm(initialForm); window.setTimeout(() => setSubmitted(false), 3500); };
  return <SectionWrapper id="contact" className="border-t border-line"><div className="grid gap-16 lg:grid-cols-[0.9fr_1.1fr] lg:gap-24"><div><p className="eyebrow">Get in touch</p><h2 className="section-title">Let’s build something exceptional together.</h2><p className="mt-8 max-w-md text-sm leading-7 text-stone-400">I’m open to thoughtful product work, engineering roles, and collaborations where craft and clarity matter.</p><div className="mt-12 border-y border-line py-6 text-sm text-stone-300"><div className="flex gap-3"><MapPin className="mt-0.5 h-4 w-4 text-accent" /><div><p className="text-xs uppercase tracking-[0.16em] text-stone-500">Based in</p><p className="mt-1">Nairobi, Kenya · available remotely</p></div></div></div><dl className="mt-8 space-y-5">{details.map(({ icon: Icon, label, value, href }) => <div key={label} className="flex items-start gap-3"><Icon className="mt-0.5 h-4 w-4 text-stone-500" /><div><dt className="text-[10px] font-bold uppercase tracking-[0.18em] text-stone-500">{label}</dt><dd className="mt-1"><a className="text-sm text-stone-300 transition-colors hover:text-accent" href={href} target={href.startsWith('http') ? '_blank' : undefined} rel="noreferrer">{value}</a></dd></div></div>)}</dl></div><form onSubmit={handleSubmit} className="self-end"><div className="grid gap-x-8 sm:grid-cols-2"><Field label="Name" id="name" value={form.name} onChange={updateField('name')} /><Field label="Email" id="email" type="email" value={form.email} onChange={updateField('email')} /></div><Field label="Subject" id="subject" value={form.subject} onChange={updateField('subject')} /><label className="mt-8 block"><span className="text-[10px] font-bold uppercase tracking-[0.18em] text-stone-500">Message</span><textarea id="message" required rows={5} value={form.message} onChange={updateField('message')} placeholder="Tell me about the work." className="mt-3 w-full resize-none border-b border-line bg-transparent pb-3 text-sm leading-7 text-paper outline-none placeholder:text-stone-600 focus:border-accent" /></label><button type="submit" disabled={submitted} className="btn-primary mt-10">{submitted ? 'Message received' : 'Send inquiry'} <ArrowUpRight className="h-4 w-4" /></button></form></div></SectionWrapper>;
}
interface FieldProps { label: string; id: ContactField; type?: 'text' | 'email'; value: string; onChange: (event: ChangeEvent<HTMLInputElement>) => void; }
function Field({ label, id, type = 'text', value, onChange }: FieldProps) { return <label className="mt-8 block"><span className="text-[10px] font-bold uppercase tracking-[0.18em] text-stone-500">{label}</span><input id={id} required type={type} value={value} onChange={onChange} className="mt-3 w-full border-b border-line bg-transparent pb-3 text-sm text-paper outline-none placeholder:text-stone-600 focus:border-accent" placeholder={label === 'Name' ? 'Your name' : label === 'Email' ? 'you@company.com' : 'A short introduction'} /></label>; }
