import { motion } from 'framer-motion';
import { ArrowUpRight, Github, Globe2 } from 'lucide-react';
import SectionWrapper from './SectionWrapper';

interface Project { title: string; description: string; tech: string[]; github?: string; liveDemo?: string; }

const projects: Project[] = [
  { title: 'Samaki Soko', description: 'A marketplace platform for coastal fishermen to market their catch and support accessible discovery.', tech: ['JavaScript', 'REST APIs', 'CSS', 'HTML'], github: 'https://github.com/abdalla-dev453/samaki-sokoapp' },
  { title: 'Expense Tracker', description: 'A personal finance web application for recording and understanding day-to-day spending.', tech: ['JavaScript', 'HTML', 'CSS'], github: 'https://github.com/abdalla-dev453/expensetracker' },
  { title: 'Portfolio Website', description: 'A fast, responsive portfolio built with a content-first user experience.', tech: ['React', 'TypeScript', 'Framer Motion', 'Vite'], github: 'https://github.com/abdalla-dev453/my-portfolio-website', liveDemo: '/' },
];

export default function Projects() {
  return <SectionWrapper id="projects" className="border-y border-line"><div className="mb-14 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow">Selected work</p><h2 className="section-title">Projects built for real use.</h2></div><p className="max-w-md text-sm leading-7 text-stone-400">Each project is approached with clarity, maintainability, and the people using it in mind.</p></div><div className="grid gap-5 lg:grid-cols-3">{projects.map((project, index) => <motion.article key={project.title} initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.2 }} transition={{ delay: index * 0.08 }} className="group flex min-h-[340px] flex-col border border-line bg-card p-6 transition duration-300 hover:-translate-y-1 hover:border-accent hover:shadow-[0_18px_40px_rgba(27,72,53,.1)]"><div className="flex items-start justify-between"><span className="font-mono text-xs font-bold tracking-[0.16em] text-accent">0{index + 1}</span><span className="grid h-10 w-10 place-items-center rounded-full border border-line text-forest transition-colors group-hover:border-accent group-hover:bg-sun"><Globe2 className="h-4 w-4" aria-hidden="true" /></span></div><div className="mt-12"><h3 className="text-2xl font-bold tracking-[-.035em] text-paper">{project.title}</h3><p className="mt-3 text-sm leading-6 text-stone-400">{project.description}</p></div><ul className="mt-6 flex flex-wrap gap-2">{project.tech.map((tech) => <li key={tech} className="border border-line px-2.5 py-1 text-[10px] font-bold uppercase tracking-[0.12em] text-stone-400">{tech}</li>)}</ul><div className="mt-auto flex flex-wrap gap-x-5 gap-y-3 pt-8">{project.github && <a href={project.github} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.13em] text-forest hover:text-accent"><Github className="h-4 w-4" aria-hidden="true" /> Source</a>}{project.liveDemo && <a href={project.liveDemo} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.13em] text-forest hover:text-accent"><ArrowUpRight className="h-4 w-4" aria-hidden="true" /> Live demo</a>}</div></motion.article>)}</div></SectionWrapper>;
}
