import { motion } from 'framer-motion';
import { ArrowUpRight, Github } from 'lucide-react';
import SectionWrapper from './SectionWrapper';
interface Project { title: string; description: string; tech: string[]; image: string; github: string; demo: string; }
const projects: Project[] = [
  { title: 'E-Commerce Platform', description: 'A full-stack storefront with product management, cart workflows, and secure checkout.', tech: ['React', 'Flask', 'PostgreSQL', 'Tailwind'], image: 'https://images.pexels.com/photos/230544/pexels-photo-230544.jpeg?auto=compress&cs=tinysrgb&w=1200', github: 'https://github.com/bhokemwita/Project-Showcase-App', demo: '#' },
  { title: 'Expense Tracking App', description: 'A focused workspace for teams to record activity, manage tasks, and maintain momentum.', tech: ['React', 'Node.js', 'SQLite', 'REST API'], image: 'https://images.pexels.com/photos/669619/pexels-photo-669619.jpeg?auto=compress&cs=tinysrgb&w=1200', github: '#', demo: '#' },
  { title: 'Samaki Soko', description: 'A responsive marketplace experience designed around accessible browsing and clear business workflows.', tech: ['JavaScript', 'REST APIs', 'CSS', 'HTML'], image: 'https://images.pexels.com/photos/1268855/pexels-photo-1268855.jpeg?auto=compress&cs=tinysrgb&w=1200', github: 'https://github.com/abdalla-dev453/samaki-soko-app', demo: '#' },
  { title: 'Portfolio Website', description: 'This deliberately restrained portfolio: responsive, accessible, and built for the work to lead.', tech: ['React', 'TypeScript', 'Framer Motion', 'Vite'], image: 'https://images.pexels.com/photos/196645/pexels-photo-196645.jpeg?auto=compress&cs=tinysrgb&w=1200', github: 'https://github.com/abdalla-dev453/my-portfolio-website', demo: '#' },
];
export default function Projects() { return <SectionWrapper id="projects" className="border-y border-line"><div className="mb-16 grid gap-6 md:grid-cols-2"><div><p className="eyebrow">Selected work</p><h2 className="section-title">Useful systems, made with intent.</h2></div><p className="self-end max-w-md text-sm leading-7 text-stone-400">A selection of products where the goal was more than a polished interface: better decisions, clearer operations, and a reliable experience.</p></div><div className="divide-y divide-line border-y border-line">{projects.map((project, index) => <motion.article key={project.title} initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * 0.06 }} className="group grid gap-7 py-10 md:grid-cols-[150px_1fr_230px] md:items-center"><p className="font-display text-5xl text-stone-600">0{index + 1}</p><div><h3 className="text-3xl text-paper">{project.title}</h3><p className="mt-3 max-w-xl text-sm leading-6 text-stone-400">{project.description}</p><ul className="mt-5 flex flex-wrap gap-x-4 gap-y-2">{project.tech.map((tech) => <li key={tech} className="text-[10px] font-bold uppercase tracking-[0.15em] text-accent">{tech}</li>)}</ul></div><div className="overflow-hidden border border-line"><img src={project.image} alt="" className="aspect-[16/10] w-full object-cover transition duration-500 group-hover:scale-105" loading="lazy" /></div><div className="md:col-start-2 flex gap-5"><a href={project.github} className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.15em] text-stone-300 hover:text-accent"><Github className="h-4 w-4" /> Source</a>{project.demo !== '#' && <a href={project.demo} className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.15em] text-stone-300 hover:text-accent">Visit <ArrowUpRight className="h-4 w-4" /></a>}</div></motion.article>)}</div></SectionWrapper>; }
