import { Blocks, Gauge, LayoutTemplate, ShieldCheck, Sparkles } from 'lucide-react';
import SectionWrapper from './SectionWrapper';

const services = [
  { icon: LayoutTemplate, number: '01', title: 'Website design & build', text: 'Responsive marketing websites that clearly communicate your offer and guide visitors to take action.' },
  { icon: Blocks, number: '02', title: 'Web applications', text: 'Reliable, custom interfaces and APIs for workflows that need more than a standard website.' },
  { icon: Gauge, number: '03', title: 'Performance & refinement', text: 'Focused improvements to speed, usability, accessibility, and the details that build trust.' },
  { icon: ShieldCheck, number: '04', title: 'Security-minded delivery', text: 'Thoughtful implementation, secure defaults, and practical attention to data and integrations.' }
];

export default function Services() { return <SectionWrapper id="services" className="overflow-hidden border-t border-line bg-[#f3f5f1]"> <div className="relative"> <div className="pointer-events-none absolute -right-20 -top-24 h-64 w-64 rounded-full bg-sun/10 blur-3xl" /> <div className="relative"> <div className="mb-5 inline-flex items-center gap-2 rounded-full bg-ink px-3 py-2 text-[10px] font-bold uppercase tracking-[.18em] text-accent"><Sparkles className="h-3.5 w-3.5" aria-hidden="true" /> Thoughtful by design</div><div className="mb-12 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">Services</p><h2 className="section-title max-w-3xl">A sharper digital presence, built to last.</h2></div><p className="max-w-md text-sm leading-7 text-stone-400">From a focused website to a data-backed product, every engagement starts with a clear scope and practical plan.</p></div><div className="grid gap-px border border-line bg-line md:grid-cols-2">{services.map(({ icon: Icon, number, title, text }, index) => <article key={title} className={`group relative min-h-[250px] overflow-hidden p-7 transition-colors hover:bg-[#24563f] sm:p-9 ${index < 2 ? 'border-b border-white/15' : ''} ${index % 2 === 0 ? 'md:border-r md:border-white/15' : ''}`}><span className="absolute -right-3 -top-8 font-display text-[9rem] font-bold leading-none text-white/[.05]">{number}</span><div className="relative flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-full bg-sun text-forest"><Icon className="h-5 w-5" aria-hidden="true" /></span><span className="font-mono text-xs text-sun">/{number}</span></div><h3 className="relative mt-12 text-2xl font-bold tracking-[-.035em] text-ink">{title}</h3><p className="relative mt-3 max-w-md text-sm leading-6 text-white/65">{text}</p></article>)}</div></div></div></SectionWrapper>; }
